[app]
name = "EMFMon"
category = "Games"

[entry]
class = "EMFMon"

[metadata]
author = "DroppedSyn"
license = "MIT"
url = "https://github.com/DroppedSyn/emfmon"
description = "Grow a mon. Build its moveset. Fight the badge next to you. Collect battlepoints."
version = "2.0.0"
